{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Reported Frauds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "reported_frauds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fraud Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "fraud_trend", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "fraud_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fraud Predicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "fraud_trend > 0.7", "legendFormat": "__auto" }
   ]
  }
 ]
}